// Generated by CoffeeScript 1.9.1
var expect, file_type, fs, node_env,
  hasProp = {}.hasOwnProperty;

fs = require('fs');

require('mocha');

expect = require('chai').expect;

node_env = process.env.NODE_ENV;

file_type = process.env.FILE_TYPE;

describe("config read test", function() {
  before(function() {
    try {
      return fs.unlinkSync("config");
    } catch (_error) {}
  });
  after(function() {
    try {
      return fs.unlinkSync("config");
    } catch (_error) {}
  });
  return it("read dir", function() {
    var config, key, results, val;
    fs.symlinkSync("./test/many_types", "config");
    config = require('../index');
    results = [];
    for (key in config) {
      if (!hasProp.call(config, key)) continue;
      val = config[key];
      expect(val.lang).to.eql(key);
      if (node_env) {
        results.push(expect(val.env).to.eql(node_env));
      } else {
        results.push(expect(val.env).to.eql("development"));
      }
    }
    return results;
  });
});
