// Generated by CoffeeScript 1.9.1
var expect, file_type, fs, node_env;

fs = require('fs');

require('mocha');

expect = require('chai').expect;

node_env = process.env.NODE_ENV;

file_type = process.env.FILE_TYPE;

describe("config read test", function() {
  before(function() {
    try {
      return fs.unlinkSync("config");
    } catch (_error) {}
  });
  after(function() {
    try {
      return fs.unlinkSync("config");
    } catch (_error) {}
  });
  return it("read config file " + node_env + ", " + file_type, function() {
    var config;
    fs.symlinkSync("./test/" + file_type, "config");
    config = require('../index');
    if (node_env) {
      expect(config.env).to.eql(node_env);
    } else {
      expect(config.env).to.eql("development");
    }
    return expect(config.lang).to.eql(file_type);
  });
});
