// Generated by CoffeeScript 1.6.2
(function() {
  var config, fs, load;

  fs = require('fs');

  config = null;

  load = function(mode) {
    var file, files, _i, _len, _results;

    mode || (mode = process.env.NODE_ENV || "development");
    config = require("../../config/" + mode);
    if (!fs.existsSync("./config/" + mode + "/")) {
      return;
    }
    files = fs.readdirSync("./config/" + mode + "/");
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      file = file.replace(/\.js$/, "");
      file = file.replace(/\.coffee$/, "");
      file = file.replace(/\.json$/, "");
      _results.push(config[file] = require("../../config/" + mode + "/" + file));
    }
    return _results;
  };

  load();

  config._load = load;

  module.exports = config;

}).call(this);
